// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4F3aTKO6eaqTiUtfXgFHBX9K5a8neh1Q',
    appId: '1:1070299251679:web:37e2d751a965a12a15ba6a',
    messagingSenderId: '1070299251679',
    projectId: 'alertnet-36777',
    authDomain: 'alertnet-36777.firebaseapp.com',
    storageBucket: 'alertnet-36777.firebasestorage.app',
    measurementId: 'G-ZG2RQKHZ25',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqUBN---y7TLpe_JV91Qciwim__wJipNU',
    appId: '1:1070299251679:android:fcd8a9a3fdbe4bbf15ba6a',
    messagingSenderId: '1070299251679',
    projectId: 'alertnet-36777',
    storageBucket: 'alertnet-36777.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4F3aTKO6eaqTiUtfXgFHBX9K5a8neh1Q',
    appId: '1:1070299251679:web:be51332617e11dc415ba6a',
    messagingSenderId: '1070299251679',
    projectId: 'alertnet-36777',
    authDomain: 'alertnet-36777.firebaseapp.com',
    storageBucket: 'alertnet-36777.firebasestorage.app',
    measurementId: 'G-45RYEWVLK5',
  );
}
